baseURL = 'https://ambuje.github.io/'
languageCode = 'en-us'
title = 'Ambuje Gupta'
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Personal portfolio and blog"
  author = "Your Name"
  showReadingTime = true
  showShareButtons = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/yourusername"
  
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/yourprofile"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/Ambuje_resume.pdf"
    weight = 20
  
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
